### ISSUE TITLE
hugo のテーマファイルに使用してもいいですか？

### ISSUE THREAD

**Issue by ress997** [a-know/grass-graph#30]
記事を読みましたがサーバーの余っているリソースを使用してると書いておりテーマファイルに含めると負荷が増えると思われるため相談しました。

ちなみに使用したいテーマファイルは https://github.com/MeiK2333/github-style です。

**Comment by a-know** [comment]
@ress997 
おもしろそうですね！ぜひご利用ください！ 😄

**Comment by a-know** [comment]
ちなみに、最近 https://pixe.la というサービスの方に力をいれていまして、こちらだと記事の更新数とかpv数とかもグラフ化できるのでさらにおもしろいかな？と思いました！ご参考まで！ @ress997
