### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ghost** [a-know/grass-graph#31]
I customize my colors so they look like this:

![Untitled](https://user-images.githubusercontent.com/926619/71384802-1463b180-25a9-11ea-8de9-b40b95c14125.png)

https://github.com/cup/hearth/blob/37062ec6/stylus/github.user.css#L7-L34

I think that would be a good option for this tool

**Comment by a-know** [comment]
@cup 
Thank you for feedback! Sorry for my late reply.

The current specification of grass-graph obtains a graph by scraping the GitHub profile page. Therefore, I will not be able to accept the options you suggested.（I want to keep this tool simple :) ）

With Pixela ( https://github.com/a-know/Pixela , https://pixe.la ) I made, you can choose a color pattern. Please, try it! :)
