### ISSUE TITLE
No image

### ISSUE THREAD

**Issue by maxcramer** [a-know/grass-graph#33]
Image links or images not generating properly, just appearing blank oblong

**Comment by a-know** [comment]
@maxcramer 
I know what's going on! Please wait for a while until I restore it!

**Comment by a-know** [comment]
@maxcramer 
Thank you for waiting! It seems to be restored because I renovated it.
Can you check it? If the problem is resolved, please close this issue.

**Comment by maxcramer** [comment]
yeah all working great job
