### ISSUE TITLE
What is the license type for this repository?

### ISSUE THREAD

**Issue by KaitakuShiba** [a-know/grass-graph#38]
Hello, thank you for your good service!
What is the license type for this repository?
I don't think I've seen it mentioned anywhere, so if you have decided, I'd appreciate it.

**Comment by a-know** [comment]
@KaitakuShiba 
Hello! Thank you for question!

The difficult thing to consider about licensing this repository is that the Grass-Graph site(https://grass-graph.moshimo.works/) design uses a paid bootstrap theme.
Do you have any good ideas? Thank you.

**Comment by KaitakuShiba** [comment]
@a-know 
I see. So that's the situation.
I'm afraid I'm not too bright on the front end, but are you using the paid theme for the LP part?
In my case, I wanted to re-write the grass imaging logic for using package(Python version), so I thought it would be good if I could separate the image generation logic from the LP including the paid theme if possible.
However, upon closer examination of the application, I found that using [Pixela](https://pixe.la/ja) would be better, so I think I will use Pixela for now.
Thank you very much for your answer.

**Comment by a-know** [comment]
@KaitakuShiba 
I see! Your suggestion that separate repository is sounds good.

I'm glad to your using Pixela 😄
