### ISSUE TITLE
API support for fetching the Image

### ISSUE THREAD

**Issue by rahulbansal16** [a-know/grass-graph#39]
Hi,

Thanks for building this tool. Do you plan to add API support to it?

**Comment by a-know** [comment]
@rahulbansal16 
Thank you for comment, but I don't understand what you comment mean, sorry 😓 

By requesting `https://grass-graph.moshimo.works/images/<YOUR GITHUB ID>.png` , you can fetch the images at any time.
Is there anything insufficient in this?

**Comment by rahulbansal16** [comment]
@a-know I am sorry, It's my mistake. You are right the API exists.
