### ISSUE TITLE
Bringing this to the attention of others...

### ISSUE THREAD

**Issue by al-the-x** [a-know/grass-graph#4]
Haven't tried deploying to Heroku yet, but thank you for making this! /cc @kytrinyx

**Comment by al-the-x** [comment]
Was just chatting with @kytrinyx about this very same idea. So glad I thought to Google before creating [Yet Another Standard](http://xkcd.com/927/)...!

**Comment by kytrinyx** [comment]
Nice! Great find, @al-the-x

**Comment by a-know** [comment]
Thank you so much for your great message! @al-the-x @kytrinyx 
But now, I recommend to use [Grass-Graph](https://grass-graph.shitemil.works) because make free from github update.
Please use this!

I want many people to use this, too.
Do you have any good ideas? 😄
