### ISSUE TITLE
Day of the week display is wrong

### ISSUE THREAD

**Issue by ytkg** [a-know/grass-graph#43]
Hi! Thanks for the nice product.

![image](https://user-images.githubusercontent.com/12048864/178751904-3dfa1237-b9a3-4da7-b40e-259e9cc9d93e.png)

Has https://github.com/a-know/grass-graph/pull/36 been released?

**Comment by a-know** [comment]
@ytkg 
Thank you for reporting!

yeah, #36 had already released, so this is a newly problem.
(Maybe github profile page have some modified)

It is necessary to fix :(

**Comment by ytkg** [comment]
Hi!
I'd just like to know if there are any plans to fix this, or should we consider looking for alternate services.

**Comment by a-know** [comment]
@ytkg 
Sorry for leaving this!
I may have time to handle this problem during the year-end holidays period 🙏 🙏

**Comment by a-know** [comment]
Sorry for letting you wait.
I've just fixed this issue. Please confirm and close this issue. Thanks

https://github.com/a-know/grass-graph/pull/44

**Comment by ytkg** [comment]
Thank you for the fix!
