### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ytkg** [a-know/grass-graph#45]
Hi! thanks for nice product.

I'm getting a 502 Bad Gateway error
https://grass-graph.appspot.com/images/ytkg.png

**Comment by a-know** [comment]
Thank you for letting me know.

I tried to fix the problem, then I found that GitHub had changed their contributions graph from svg-made to table-tag-made.

<img width="1329" alt="Screenshot 2023-07-17 at 20 30 55" src="https://github.com/a-know/grass-graph/assets/1097533/c9c9d167-72a5-4d8b-9eab-fc7962a6c22b">


Grass-Graph is the service which scrapes the graph svg and convert it to png.
In other words, ... Grass-Graph became to be no longer provide your graph image as a service.

I'm very sorry, but I hope you understand. Thanks.

**Comment by ytkg** [comment]
Thank you for your support so far!
